name: 'Troubleshooting'

on:
  workflow_dispatch:
    inputs:
      useLatestTroubleshooting:
        description: Use the latest troubleshooting action from https://github.com/microsoft/AL-Go
        type: boolean
        default: false

permissions:
  contents: write
  actions: read

defaults:
  run:
    shell: powershell

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  Troubleshooting:
    name: freddydk/AL-Go/Actions/TroubleShooting@checkSecrets
    if: github.event.inputs.useLatestTroubleshooting == 'false'
    runs-on: [ windows-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Troubleshooting
        uses: freddydk/AL-Go/Actions/TroubleShooting@checkSecrets
        with:
          shell: powershell
          gitHubSecrets: ${{ toJson(secrets) }}

  LatestTroubleshooting: 
    name: microsoft/AL-Go/Actions/TroubleShooting@main
    if: github.event.inputs.useLatestTroubleshooting == 'true'
    runs-on: [ windows-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Troubleshooting
        uses: microsoft/AL-Go/Actions/TroubleShooting@main
        with:
          shell: powershell
          gitHubSecrets: ${{ toJson(secrets) }}
